apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
